In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from citipy import citipy
from pprint import pprint

In [6]:
# Create a set of random latitude and longitude combinations.
lats = np.random.uniform(low=-90.000, high=90.000, size=2000)
lngs = np.random.uniform(low=-180.000, high=180.000, size=2000)
lat_lngs = zip(lats, lngs)
lat_lngs

In [7]:
# Add the latitudes and longitudes to a list.
coordinates = list(lat_lngs)

In [8]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

765

In [9]:
# Import the requests library.
import requests

# Import the API key.
from config import weather_api_key

In [10]:
# Basic URL for the OpenWeatherMap with the weather_api_key added to the URL
url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + weather_api_key

In [11]:
# Create an empty list to hold the weather data.
city_data = []
# Print the beginning of the logging.
print("Beginning Data Retrieval     ")
print("-----------------------------")
# Create counters.
record_count = 1
set_count = 1

Beginning Data Retrieval
-----------------------------

In [12]:
# Loop through all the cities in the list.
for i, city in enumerate(cities):
    try:
        # Group cities in sets of 50 for logging purposes.
        if (i % 50 == 0 and i >= 50):
            set_count += 1
            record_count = 1
        # Create endpoint URL with each city.
        city_url = url + "&q=" + city.replace(" ","+")
        # Parse the JSON and retrieve data.
        city_weather = requests.get(city_url).json()
        # Parse out the needed data.
        city_lat = city_weather["coord"]["lat"]
        city_lng = city_weather["coord"]["lon"]
        city_max_temp = city_weather["main"]["temp_max"]
        city_humidity = city_weather["main"]["humidity"]
        city_clouds = city_weather["clouds"]["all"]
        city_wind = city_weather["wind"]["speed"]
        city_country = city_weather["sys"]["country"]
        city_description = city_weather['weather'][0]['description']
        # Append the city information into city_data list.
        city_data.append({"City": city.title(),
                          "Lat": city_lat,
                          "Lng": city_lng,
                          "Max Temp": city_max_temp,
                          "Humidity": city_humidity,
                          "Cloudiness": city_clouds,
                          "Wind Speed": city_wind,
                          "Country": city_country,
                          "Current Description": city_description})
    # If an error is experienced, skip the city.
    except:
        print("City not found. Skipping...")
        pass
    
    
    
    # Log the URL, record, and set numbers and the city.
    #print(f"Processing Record {record_count} of Set {set_count} | {city}")
    # Add 1 to the record count.
    record_count += 1
    
    
# Indicate that Data Loading is complete.
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
City not found. Skipping...
-----------------------------
Data Retrieval Complete
-----------------------------

In [13]:
len(city_data)

711

In [14]:
# Convert the array of dictionaries to a Pandas DataFrame.
city_data_df = pd.DataFrame(city_data)
city_data_df.head(10)

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
0,Tasiilaq,65.6145,-37.6368,33.96,76,100,7.00,GL,overcast clouds
1,Butaritari,3.0707,172.7902,83.26,76,9,17.67,KI,clear sky
2,Ushuaia,-54.8000,-68.3000,44.26,76,75,13.80,AR,light rain
3,Saint George,37.1041,-113.5841,79.39,22,1,1.01,US,clear sky
4,San Patricio,28.0170,-97.5169,75.81,58,0,4.70,US,clear sky
5,Bluff,-46.6000,168.3333,50.81,77,100,10.80,NZ,overcast clouds
6,Severo-Kurilsk,50.6789,156.1250,48.76,95,100,23.38,RU,light rain
7,El Alto,-4.2714,-81.2147,63.10,84,92,9.24,PE,overcast clouds
8,Shetpe,44.1667,52.1167,81.68,13,0,28.30,KZ,clear sky
9,Jamestown,42.0970,-79.2353,54.07,82,90,11.01,US,overcast clouds

In [15]:
new_column_order = ["City", "Country", "Lat", "Lng", "Max Temp", "Humidity", "Cloudiness", "Wind Speed", "Current Description"]

In [16]:
city_data_df = city_data_df[new_column_order]
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,Tasiilaq,GL,65.6145,-37.6368,33.96,76,100,7.00,overcast clouds
1,Butaritari,KI,3.0707,172.7902,83.26,76,9,17.67,clear sky
2,Ushuaia,AR,-54.8000,-68.3000,44.26,76,75,13.80,light rain
3,Saint George,US,37.1041,-113.5841,79.39,22,1,1.01,clear sky
4,San Patricio,US,28.0170,-97.5169,75.81,58,0,4.70,clear sky
5,Bluff,NZ,-46.6000,168.3333,50.81,77,100,10.80,overcast clouds
6,Severo-Kurilsk,RU,50.6789,156.1250,48.76,95,100,23.38,light rain
7,El Alto,PE,-4.2714,-81.2147,63.10,84,92,9.24,overcast clouds
8,Shetpe,KZ,44.1667,52.1167,81.68,13,0,28.30,clear sky
9,Jamestown,US,42.0970,-79.2353,54.07,82,90,11.01,overcast clouds

In [17]:
# Create the output file (CSV).
output_data_file = "WeatherPy_Database.csv"
# Export the City_Data into a CSV.
city_data_df.to_csv(output_data_file)